
package org.jboss.jboss_jdf.jboss_as_quickstart.wsat.simple.restaurant;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4.redhat-621090
 * 2016-12-19T20:59:11.908+05:30
 * Generated source version: 3.0.4.redhat-621090
 */

@WebFault(name = "RestaurantException", targetNamespace = "http://www.jboss.org/jboss-jdf/jboss-as-quickstart/wsat/simple/Restaurant")
public class RestaurantException_Exception extends Exception {
    
    private org.jboss.jboss_jdf.jboss_as_quickstart.wsat.simple.restaurant.RestaurantException restaurantException;

    public RestaurantException_Exception() {
        super();
    }
    
    public RestaurantException_Exception(String message) {
        super(message);
    }
    
    public RestaurantException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public RestaurantException_Exception(String message, org.jboss.jboss_jdf.jboss_as_quickstart.wsat.simple.restaurant.RestaurantException restaurantException) {
        super(message);
        this.restaurantException = restaurantException;
    }

    public RestaurantException_Exception(String message, org.jboss.jboss_jdf.jboss_as_quickstart.wsat.simple.restaurant.RestaurantException restaurantException, Throwable cause) {
        super(message, cause);
        this.restaurantException = restaurantException;
    }

    public org.jboss.jboss_jdf.jboss_as_quickstart.wsat.simple.restaurant.RestaurantException getFaultInfo() {
        return this.restaurantException;
    }
}
