package org.jboss.jboss_jdf.jboss_as_quickstart.wsat.simple.restaurant;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4.redhat-621090
 * 2016-12-19T20:59:11.946+05:30
 * Generated source version: 3.0.4.redhat-621090
 * 
 */
@WebService(targetNamespace = "http://www.jboss.org/jboss-jdf/jboss-as-quickstart/wsat/simple/Restaurant", name = "RestaurantServiceAT")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface RestaurantServiceAT {

    @WebMethod
    public void makeBooking() throws RestaurantException_Exception;

    @WebMethod
    public void reset();

    @WebResult(name = "return", targetNamespace = "http://www.jboss.org/jboss-jdf/jboss-as-quickstart/wsat/simple/Restaurant", partName = "return")
    @WebMethod
    public int getBookingCount();
}
