
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.jboss.jboss_jdf.jboss_as_quickstart.wsat.simple.restaurant;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4.redhat-621090
 * 2016-12-19T20:59:11.927+05:30
 * Generated source version: 3.0.4.redhat-621090
 * 
 */

@javax.jws.WebService(
                      serviceName = "RestaurantServiceATService",
                      portName = "RestaurantServiceAT",
                      targetNamespace = "http://www.jboss.org/jboss-jdf/jboss-as-quickstart/wsat/simple/Restaurant",
                      wsdlLocation = "WEB-INF/wsdl/RestaurantServiceAT.wsdl",
                      endpointInterface = "org.jboss.jboss_jdf.jboss_as_quickstart.wsat.simple.restaurant.RestaurantServiceAT")
                      
public class RestaurantServiceATImpl implements RestaurantServiceAT {

    private static final Logger LOG = Logger.getLogger(RestaurantServiceATImpl.class.getName());

    /* (non-Javadoc)
     * @see org.jboss.jboss_jdf.jboss_as_quickstart.wsat.simple.restaurant.RestaurantServiceAT#makeBooking(*
     */
    public void makeBooking() throws RestaurantException_Exception    { 
        LOG.info("Executing operation makeBooking");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new RestaurantException_Exception("RestaurantException...");
    }

    /* (non-Javadoc)
     * @see org.jboss.jboss_jdf.jboss_as_quickstart.wsat.simple.restaurant.RestaurantServiceAT#reset(*
     */
    public void reset() { 
        LOG.info("Executing operation reset");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.jboss.jboss_jdf.jboss_as_quickstart.wsat.simple.restaurant.RestaurantServiceAT#getBookingCount(*
     */
    public int getBookingCount() { 
        LOG.info("Executing operation getBookingCount");
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
