package org.wsdlgetproblem.xsd.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4.redhat-621084
 * 2016-09-29T14:57:21.664+05:30
 * Generated source version: 3.0.4.redhat-621084
 * 
 */
@WebService(targetNamespace = "http://www.wsdlgetproblem.org/xsd/test/", name = "helloWorld_port")
@XmlSeeAlso({org.wsdlgetproblem.xsd.test.messages.ObjectFactory.class, org.wsdlgetproblem.xsd.test.common.ObjectFactory.class, org.wsdlgetproblem.xsd.test.content.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HelloWorldPort {

    @WebResult(name = "responseMessage", targetNamespace = "http://www.wsdlgetproblem.org/xsd/test/messages", partName = "response")
    @WebMethod(operationName = "www.wsdlgetproblem.org", action = "http://www.wsdlgetproblem.org/xsd/test/requestMessage")
    public java.lang.String wwwWsdlgetproblemOrg(
        @WebParam(partName = "request", name = "requestMessage", targetNamespace = "http://www.wsdlgetproblem.org/xsd/test/messages")
        org.wsdlgetproblem.xsd.test.common.CommonRequestType request
    );
}
