
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.wsdlgetproblem.xsd.test;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4.redhat-621084
 * 2016-09-29T14:57:21.632+05:30
 * Generated source version: 3.0.4.redhat-621084
 * 
 */

@javax.jws.WebService(
                      serviceName = "helloWorldService",
                      portName = "helloWorld_port",
                      targetNamespace = "http://www.wsdlgetproblem.org/xsd/test/",
                      wsdlLocation = "wsdl/helloWorld.wsdl",
                      endpointInterface = "org.wsdlgetproblem.xsd.test.HelloWorldPort")
                      
public class HelloWorld_PortImpl implements HelloWorldPort {

    private static final Logger LOG = Logger.getLogger(HelloWorld_PortImpl.class.getName());

    /* (non-Javadoc)
     * @see org.wsdlgetproblem.xsd.test.HelloWorldPort#wwwWsdlgetproblemOrg(org.wsdlgetproblem.xsd.test.common.CommonRequestType  request )*
     */
    public java.lang.String wwwWsdlgetproblemOrg(org.wsdlgetproblem.xsd.test.common.CommonRequestType request) { 
        LOG.info("Executing operation wwwWsdlgetproblemOrg");
        System.out.println(request);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
