
package  mil.navy.erm.nsips.mydeployment;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SimpleService", targetNamespace = "urn:mil:navy:erm:ade:esb:SimpleService", wsdlLocation = "file:/C:/X/SANDBOX/WS_SIMPLE_WS/web/WEB-INF/wsdl/SimpleService.wsdl")
public class SimpleService_Service
    extends Service
{

    private final static URL SIMPLESERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMPLESERVICE_EXCEPTION;
    private final static QName SIMPLESERVICE_QNAME = new QName("urn:mil:navy:erm:ade:esb:SimpleService", "SimpleService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/X/SANDBOX/WS_SIMPLE_WS/web/WEB-INF/wsdl/SimpleService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMPLESERVICE_WSDL_LOCATION = url;
        SIMPLESERVICE_EXCEPTION = e;
    }

    public SimpleService_Service() {
        super(__getWsdlLocation(), SIMPLESERVICE_QNAME);
    }

    public SimpleService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMPLESERVICE_QNAME, features);
    }

    public SimpleService_Service(URL wsdlLocation) {
        super(wsdlLocation, SIMPLESERVICE_QNAME);
    }

    public SimpleService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMPLESERVICE_QNAME, features);
    }

    public SimpleService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimpleService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SimpleService
     */
    @WebEndpoint(name = "SimpleServicePort")
    public SimpleService getSimpleServicePort() {
        return super.getPort(new QName("urn:mil:navy:erm:ade:esb:SimpleService", "SimpleServicePort"), SimpleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimpleService
     */
    @WebEndpoint(name = "SimpleServicePort")
    public SimpleService getSimpleServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:mil:navy:erm:ade:esb:SimpleService", "SimpleServicePort"), SimpleService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMPLESERVICE_EXCEPTION!= null) {
            throw SIMPLESERVICE_EXCEPTION;
        }
        return SIMPLESERVICE_WSDL_LOCATION;
    }

}
